### ISSUE TITLE
[3.1.0.9] Tier 2 Progression step impossible due to removal of Mana Crystals

### ISSUE THREAD

**Issue by nanakisan** [Mithion/Mana-And-Artifice#1131]
**Describe the bug (MANDATORY):**
Per the title. There's a progression step that is impossible because of the removal of the mana crystal. This by proxy also makes progression to tier 3 impossible if a server / modpack has all progress goals required.

**To Reproduce (MANDATORY):**
Steps to reproduce the behavior, e.g.:
1. Progress to tier 2
2. Do all progression steps up till craft mana crystal at manaweaving altar

**Expected behavior (MANDATORY):**
Be able to progress to tier 3

**Screenshots**

![Image](https://github.com/user-attachments/assets/2f82e64a-5e05-439e-b5ca-9defefc94955)

**Version Information (MANDATORY):**

   - Mod Version: 3.1.0.9
   - Forge Version: 47.3.0

**Additional context**
Add any other context about the problem here.  Other mods, etc.  For crash reports please use a service like https://pastebin.com/ or https://hastebin.com/.

**Comment by Mithion** [comment]
Fixed in version 3.1.10

**Comment by Shibva** [comment]
@Mithion The recipe for the Mana Crystal still exists in JEI. I think you forgot to remove that recipie file (somehow its still valid???)
