### ISSUE TITLE
[1.19.2] Manaweave Projector doesn't send shape to Manaweaving Altar when activated by golem

### ISSUE THREAD

**Issue by Ksandr0** [Mithion/Mana-And-Artifice#643]
**Describe the bug**
Manaweave Projector doesn't send shape to Manaweaving Altar when activated by golem.

**To Reproduce**
1. Get a faction.
2. Get tier 5.
3. Place Manaweave Projector, Manaweaving Altar, Mana Crystall, Delegation station.
4. Create a golem (construct).
5. Set a task in Delegation station to activate Manaweave Projector.
6. Make the golem to run task in Delegation station.

**Expected behavior**
Manaweave Projector send shape to Manaweaving Altar when activated by golem.

**Screenshots**
https://paste.pics/Q0GLL

**Version Information (please complete the following information):**
 - Mod Version: [2.1.0.4]
 - Forge Version [43.3.5]

**Additional context**
Game version 1.19.2

**Comment by Mithion** [comment]
After a lot of consideration I've decided to drop support for 1.19.  I can't keep up with older versions and the currently supported version.  Note that this, and many more issues have been fixed in 1.20.1 along with many new features, improvements, and QoL additions.  Sorry for the inconvenience.

**Comment by Ksandr0** [comment]
Unfortunately, on the latest available version 3.0.0.24 on version 1.20.1 the problem still exists - please check:

https://github.com/user-attachments/assets/7f76cf98-8191-4a65-a706-9e743612b01f
