### ISSUE TITLE
Too many Undead Faction mobs in the Nether 

### ISSUE THREAD

**Issue by MasonReptiloid** [Mithion/Mana-And-Artifice#672]
**Describe the bug**
Undead Faction mobs spawn in abnormally high quantities in the Nether. Hulking Zombies spawn in groups of three which make it almost impossible for other Factions to walk around. They spawn almost every minute. The strangest thing is that undead faction mobs spawn more frequently then demon faction mobs. Also fae and council faction mobs spawn in the nether as well which is a bit strange. My difficulty setting is "Normal"
P.S. not sure it is a bug but it is still a problem
**To Reproduce**
1. Go in the Nether
2. Walk around

**Expected behavior**
Less Undead Faction mobs and more Demon Faction mobs  in the Nether

**Screenshots**

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.1
 - Forge Version 47.2.0

**Additional context**

**Comment by MrGraphic** [comment]
3.0.0.3
![2024-01-08_16 03 55](https://github.com/Mithion/Mana-And-Artifice/assets/4780141/9d75b3c5-a40e-4255-b80c-2c0920abb379)
Had to use mod like InControll to cull the "heard" ;)

**Comment by MasonReptiloid** [comment]
@MrGraphic I was just scrolling through the modpack and noticed that we have "Let me despawn" installed. Tried to remove it. Seems like it solved the problem. I will return with update after our gaming session.

**Comment by MrGraphic** [comment]
Same is happening with just MNA.

**Comment by Mithion** [comment]
This is being addressed; a fix will be available soon.  Apologies, folks.

**Comment by MangriMen** [comment]
> 3.0.0.3 ![2024-01-08_16 03 55](https://private-user-images.githubusercontent.com/4780141/295029434-9d75b3c5-a40e-4255-b80c-2c0920abb379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODU4ODMsIm5iZiI6MTcwNzU4NTU4MywicGF0aCI6Ii80NzgwMTQxLzI5NTAyOTQzNC05ZDc1YjNjNS1hNDBlLTQyNTUtYjgwYy0yYzA5MjBhYmIzNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTBUMTcxOTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFkNzY2YzI3NTM0ZjI5M2FjYWE0MDM5Y2FlMTJkYjRkYjdiMzRjMDA5ZGM3ODZjZGQ5ODg4N2Y5MjczZTFmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.je7vPH85QPXSzdxtyG0mF2nfPbp1idEzbrGEwBxFMZs) Had to use mod like InControll to cull the "heard" ;)

Can you share the configuration for InControll please?

**Comment by MrGraphic** [comment]
> > 3.0.0.3 ![2024-01-08_16 03 55](https://private-user-images.githubusercontent.com/4780141/295029434-9d75b3c5-a40e-4255-b80c-2c0920abb379.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODU4ODMsIm5iZiI6MTcwNzU4NTU4MywicGF0aCI6Ii80NzgwMTQxLzI5NTAyOTQzNC05ZDc1YjNjNS1hNDBlLTQyNTUtYjgwYy0yYzA5MjBhYmIzNzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTBUMTcxOTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFkNzY2YzI3NTM0ZjI5M2FjYWE0MDM5Y2FlMTJkYjRkYjdiMzRjMDA5ZGM3ODZjZGQ5ODg4N2Y5MjczZTFmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.je7vPH85QPXSzdxtyG0mF2nfPbp1idEzbrGEwBxFMZs) Had to use mod like InControll to cull the "heard" ;)
> 
> Can you share the configuration for InControll please?

Sure!
```
[
  {
    "mob": "mna:lantern_wraith",
    "dimension": "minecraft:the_nether",
	"when": "onjoin",
    "result": "deny"
  },
  {
    "mob": "mna:hulking_zombie",
    "dimension": "minecraft:the_nether",
	"when": "onjoin",
    "result": "deny"
  },
  {
    "mob": "mna:skeleton_assassin",
    "dimension": "minecraft:the_nether",
	"when": "onjoin",
    "result": "deny"
  }
]
```
The code goes into spawn.json file
I haven't tried 3.0.0.7 yet but Mithion made some changes to spawns :).

**Comment by Mithion** [comment]
This was fixed in version 3.0.0.8.

**Comment by kitsunekaze-93** [comment]
Still an issue in 3.0.0.10, got killed 11 times by crypt stalkers and an army of Lantern wraiths ( with an absurd 125 hp each???)
the second i stepped inside the nether, cant survive even 10 seconds after entering!
[Screenshot (776)](https://github.com/Mithion/Mana-And-Artifice/assets/111128058/abe236cf-44a1-4e95-bde9-0835cd5e2abf)
