### ISSUE TITLE
Warding candle interaction with spawners

### ISSUE THREAD

**Issue by Helioux** [Mithion/Mana-And-Artifice#847]
**Describe the bug**
When warding candle is broken while lit, mobs can spawn regularly, but spawners are permanently disabled in the area

**To Reproduce**
1. place  warding candle with mob spawner in range
2. light candle
3. break candle
4. observe spawner
5. for thoroughness, move spawner with an item from another mod outside the range and observe spawner resumes function
5.1. move it back into area and observe it cease functioning

**Expected behavior**
warding candle being broken ends effect in its entirety

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - Mod Version: 3.0.0.14
 - Forge Version 47.2.23
 - Minecraft Version 1.20.1

**Additional context**
N/A

**Comment by Mithion** [comment]
Added a missed override, it should be good now.  I think.  Block breaking is still sometimes nebulous.

**Comment by Mithion** [comment]
This was fixed in 3.0.0.19

**Comment by Helioux** [comment]
Problem persists in existing worlds where lit candles were broken by the break spell after update. any fix to this possible or will i have to place candles in sheets and light/unlight them to find the tile the effect originates from?

**Comment by Helioux** [comment]
Problem persists in existing worlds after update. Where lit candles were broken by the break spell before update. any fix to this possible or will i have to place candles in sheets and light/unlight them to find the tile the effect originates from?
